baseurl = "http://www.nickvasile.com/"
languageCode = "en-us"
title = "Nick Vasile"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/nickv9"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/nicholas_v"
[[menu.main]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/nickva"

[params]
    description = "Nick Vasile"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    #[params.logo]
    #url = "logo.png"
    #width = 50
    #height = 50
    #alt = "Logo"

