---
title: Options for using dplyr to retrieve data from a Microsoft SQL
  Database
author: 'Nick Vasile'
date: '2020-05-04'
slug: different-ways-to-use-dplyr-and-dbplyr-to-retrieve-data-from-a-microsoft-sql-database
categories: []
tags: []
---

**This post is a work in progress**

## Motivation

I use R to extract data held in Microsoft SQL Server databases on a daily basis. 

When I first started I was confused by all the different ways to accomplish this task. I was a bit overwhelmed trying to choose the, "best," option given the specific job at hand.

I want to share what approaches I've landed on to solidly my thinking and to help others who may want a, "quick and dirty," list of options to get started with.

## Scope 

This post is about reading data from a database, not writing to one.

I prefer to use packages in the tidyverse so I'll focus on those packages.

While it's possible to generalize many of the concepts I write about here to other DBMS systems I will be focused exclusively on Microsoft SQL Server in the hopes this will provide simple, prescriptive guidance for those working in a similar configuration.

Many people working in an enterprise environment are probably working from machines joined to a Windows domain so my examples will be tailored to that configuration. That introduces a couple of implications:

* I won't be demonstrating how to connect from a system not joined to a Windows domain - the documentation for `DBI::dbConnect` covers that well if needed.
* I'm not writing this content from a machine that is joined to a Windows domain, and I haven't populated a Microsoft SQL database with the data I use in my examples, so for now, the results of the code won't be shown in examples.

One last thing - these are a few options I populated my toolbox with. They have served me well over the past two years as an analyst in an enterprise environment, but are definitely not the only options available.

## Option 1: Use dplyr syntax and let dbplyr handle the rest

### When I use this option

This is my default option. I do almost all of my analysis in R and this helps me avoid fragmenting my work and thoughts across different tools.

### Examples

```{r, eval = FALSE}

library(tidyverse)

con <- DBI::dbConnect(
      odbc::odbc(),
      Driver = "SQL Server",
      Server = "your_servers_host_name",
      Database = "name_of_database_you_want_to_query"
   )

# Example 1: filter rows, and retrieve selected columns
dplyr::tbl(con, "People") %>% #People is the table
  dplyr::filter(!is.na(Email), Department == "Purchasing" ) %>% 
  dplyr::select(Email, FirstName, LastName) %>% 
  # I will remove the following line if exploring the data and
  # not interested in actually retrieving all records
  dplyr::collect() 

# Example 2: join across tables, filter and retrieve selected 
# columns 

# Example 3: Summarize and count
```

## Option 2: Write SQL syntax and have dplyr and dbplyr run the query

## Option 3: Store the query in a text file and have dplyr and dbplyr run the query
